### PR TITLE
Add proposal and personal experience of GSoC2018 with CoreDNS in CNCF

### PR DESCRIPTION
**Pull request by jiachengxu**
- Add a proposal for CoreDNS.
- Share the personal experience of GSoC2018.

ref: #20 

Please feel free to leave your comments if something is unclear.

### CODE REVIEW

**Comment by xuzhaoqing** [comment]
Hi, Jiacheng`见 [resources/proposals/2018/cncf](../proposals/2018/cncf)` 这里的地址似乎有些问题，我们调整了目录结构，谢谢！

**Comment by jiachengxu** [comment]
Hi @xuzhaoqing , 谢谢提醒，已修改 😀

**Comment by xuzhaoqing** [comment]
Merged. Thanks

**Comment by jiachengxu** [comment]
You are welcome!

**Pull request merged**
